---
name: 01 Azure Landing Zones Continuous Integration
on:
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: thecloudforgedotcom/alz-mgmt-templates/.github/workflows/ci-template.yaml@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
